const DESKTOP_SCREEN = 965;
const TABLET_SCREEN = 550;
const DESKTOP_QUAN_MOVIES = 12;
const TABLET_QUAN_MOVIES = 8;
const MOBILE_QUAN_MOVIES = 5;
const DESKTOP_QUAN_MORE_MOVIES = 3;
const MOBILE_AND_TABLET_QUAN_MORE_MOVIES = 2;

export { DESKTOP_SCREEN,
    TABLET_SCREEN,
    DESKTOP_QUAN_MOVIES,
    TABLET_QUAN_MOVIES,
    MOBILE_QUAN_MOVIES,
    DESKTOP_QUAN_MORE_MOVIES,
    MOBILE_AND_TABLET_QUAN_MORE_MOVIES
};